### ISSUE TITLE
Extra assertions

### ISSUE THREAD

**Issue by bruderstein** [Munter/unexpected-dom#25]
I've been adding a number of tests to a React component (react-select), and come across a couple of things "missing" from unexpected-dom, such that I'd sometimes have ... 'queried for', ... in the assertion, and then a similar assertion I'd need  .querySelectorAll(...)

The two main cases are:

1) Checking that something doesn't exist

For example:
```
expect(domNode.querySelectorAll('.something-i-dont-want'), 'to have length', 0)
```

This seems analogous to 
```
expect(domNode, 'queried for', '.something-i-do-want', 'to have length', 1)
```

But needs to be expected differently.
It'd be nice if we could do

```
expect(domNode, 'to have no elements matching', '.something-i-dont-want')
```

The [no] could be optional, making the above test (`.something-i-do-want`) even nicer to read.

2) The second case is more complex, and maybe there's a better way. This is when I want to check for children in a particular order.
I've ended up doing
var items = domNode.querySelectorAll('.my-selector')
expect(items[0], 'to have attributes', ... )
expect(items[1], 'to have attributes', ... )

This isn't too bad, but wondered if there was a way to do it without resorting to .querySelectorAll().
I've sometimes been able to use `:nth-child(1)`, but that isn't always a solution when the selector is more complex.
 
Think I could probably manage the first point, if you're open to a PR for it?

**Comment by Munter** [comment]
Checking that something doesn't exist was a bit of a headache, as you can feel from the api. The problem here is that `to have length` assertions apply to strings and arrays, but not `undefined`, which is the return value of `querySelectorAll('.noMatches')`. I don't remember if we discussed overriding that special case and return an empty array from `queried for` if the result is undefined. Did I forget something here @papandreou?

In the second case you do this:
```js
expect(domNode, 'queried for', '.my-selector', 'to satisfy', [
  expect.it('to have attributes', ...),
  expect.it('to have attributes', ...)
])
```

**Comment by bruderstein** [comment]
I can see the issue with `queried for` - so what about a new "to have no matching elements" assertion? That should be possible to check that .querySelectorAll() returns undefined?  
Then we get cute error messages too:
```
expected <node ...> to have no elements matching '.noMatches' but returned [
  <subnode class="noMatches"></subnode>
]
```
Thanks for the hint on the second case, I'll try and convert those cases.

**Comment by bruderstein** [comment]
It's there. I just set out to add this, and 'to contain no elements matching' is there. I'll maybe send a PR for the readme :)

Thanks again :+1:
