### ISSUE TITLE
Comparing node names should be case insensitive

### ISSUE THREAD

**Issue by gertsonderby** [Munter/unexpected-dom#32]
Different platforms variously use upper- or lower-case names for nodes, for the purpose of comparison. An example:

```html
<div>
    <p>Text and things.</p>
</div>
```
The above is used as `subject`, below:
```js
expect(subject, 'to satisfy', {
    name: 'div',
    children: [ { name: 'p' } ]
});
```
In Chrome, the above will work. In IE, it will fail, as it does not recognize that `'div'` as equal to `'DIV'`.

**Comment by gertsonderby** [comment]
It appears that Chrome, Firefox and Opera use lower-case, IE/Edge and Safari use uppercase.

**Comment by papandreou** [comment]
Weird, it should already be lower casing before comparing when it's an HTML document. Maybe that detection code (`element.ownerDocument.contentType === 'text/html'`) isn't working properly.

@gertsonderby Could you check what that comes out as in the browsers that exhibit the problem?

**Comment by gertsonderby** [comment]
In IE11 and Safari 8 both, document.contentType is undefined.

**Comment by gertsonderby** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/contentType

Apparently the feature is non-standard. Not too sure how then to solve it.

**Comment by papandreou** [comment]
@gertsonderby Aha!

Could you check what `new DOMParser().parseFromString('<foo></foo>', 'text/xml').firstChild.ownerDocument.contentType` evaluates to?

**Comment by papandreou** [comment]
Falling back to `element.ownerDocument.toString() === '[object HTMLDocument]'` might work (at least I get `[object XMLDocument]` for XML documents in Chrome).

**Comment by gertsonderby** [comment]
That yields `undefined`, yet again, for IE. I expect the result will be the same for Safari.

**Comment by gertsonderby** [comment]
In Safari:
```
> new DOMParser().parseFromString('<foo></foo>', 'text/xml').firstChild.ownerDocument.toString()
< "[object Document]"
```

**Comment by papandreou** [comment]
@gertsonderby Interesting. How about `document.toString()` in those browsers (from the dev tools when viewing any HTML page)?

**Comment by gertsonderby** [comment]
That yields `"[object HTMLDocument]"`, consistently, as far as I can tell.

**Comment by papandreou** [comment]
https://github.com/Munter/unexpected-dom/pull/33
