### ISSUE TITLE
Look into using unexpecteds documentation generator

### ISSUE THREAD

**Issue by Munter** [Munter/unexpected-dom#8]

**Comment by papandreou** [comment]
https://github.com/unexpectedjs/unexpected/issues/114

I'm waiting for that as well :)

**Comment by sunesimonsen** [comment]
Sorry guys, I know we need this done :-)

**Comment by papandreou** [comment]
This has landed now and is ready for use. Check out https://github.com/unexpectedjs/unexpected-knockout/ to see how it can be used.

**Comment by sunesimonsen** [comment]
I'm building the new site.
